name: Construindo e Testando

on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            # Comentário primeiro passo
            - name: primeiro-passo
              run: |
               echo "Oi Mundo do DevOps!" | echo "Irei listar os arquivos em tela" 
            - name: segundo-passo
              run: ls -al
            - name: teste_pipe
              run: |
                echo "Hello, world!" | tee hello.txt | cat -n
